CREATE TABLE IF NOT EXISTS Subscribers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    dateOfBirth DATE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    reference VARCHAR(255) NOT NULL
);